services:
  db:
    image: postgres:16.4-bookworm
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres -d postgres # Username and database name
      interval: 3s
      start_interval: 3s
      start_period: 0s
      timeout: 10s
      retries: 5
    networks:
      - daemon
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  daemon:
    build:
      context: .
    env_file:
      - .env
      - path: .env.docker # If there is an additional env file to use for Docker
        required: false
    volumes:
      - ./data:/daemon/data
    restart: unless-stopped
    ports:
      # TODO: Expose the ports for the HTTP Pipes
      - 27451:27451
    depends_on:
      db:
        condition: service_healthy
    networks:
      - daemon

networks:
  daemon:
    driver: bridge
